apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: perspex-local
servers: 1
agents: 2
#kubeAPI:
#  host: "myhost.my.domain"
#  hostIP: "127.0.0.1"
#  hostPort: "6450"
ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "50000"
  config: |
    mirrors:
      "registry.local":
        endpoint:
          - http://registry.local:5000
