---
{{- if .Values.contour.enabled -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  virtualhost:
    fqdn: {{ .Values.contour.host }}
  routes:
  - conditions:
    {{- range  .Values.contour.paths }}
      - prefix: {{ . | quote }}
    {{- end }}
    services:
    - name: {{ include "backend.fullname" . }}
      port: {{ .Values.service.port }}
      protocol: {{ .Values.contour.protocol }}
{{- end }}