{{- if .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  grpcWeb:
    allowOrigins:
      - "*"
{{- end }}