apiVersion: v2
name: perspex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: backend
  condition: backend.enabled
  version: 0.1.0
- name: gateway
  condition: gateway.enabled
  version: 0.1.0
- name: contour
  repository: https://charts.bitnami.com/bitnami
  version: 10.1.3
  condition: contour.enabled
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.2
  condition: postgresql.enabled
