apiVersion: v2
name: perspex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: backend
  condition: backend.enabled
  version: 0.1.0
- name: frontend
  condition: frontend.enabled
  version: 0.1.0
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.2
  condition: postgresql.enabled
