name: backend-codegen-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
jobs:
  backend-codegen-linter:
    name: Backend Codegen Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update checkout
        run: git fetch --prune
        shell: bash

      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: '4.14.2'
          yq-url: 'https://github.com/mikefarah/yq/releases/download/v4.14.2/yq_linux_amd64'

      - name: Set environment variables
        id: set-environment-variables
        run: |
          echo "TILT_BACKEND_ENABLED="false" >> $GITHUB_ENV
          echo "TILT_REMOTE_CLUSTER=True >> $GITHUB_ENV

      - name: Run helm dependency update
        run: |
          helm dependency update infrastructure/charts/perspex

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Install tilt
        run: |
          curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v0.23.1/tilt.0.23.1.linux.x86_64.tar.gz | tar -xzv tilt && \
          mv tilt /usr/local/bin/tilt

      - uses: AbsaOSS/k3d-action@v2
        name: "Spin up k3d"
        with:
          cluster-name: "perspex-ci"
          args: >-
            -c infrastructure/tilt/k3d-config.yaml

      - name: Network
        run: |
          docker network inspect -f '{{json .Containers}}' k3d-perspex-ci | jq -r '.[] | .Name + ":" + .IPv4Address' | grep -o 'registry.localhost:[^"]*'
          registry_host=$(docker network inspect -f '{{json .Containers}}' k3d-perspex-ci | jq -r '.[] | .Name + ":" + .IPv4Address' | grep -o 'registry.localhost:[^"]*' | cut -d ":" -f2 | cut -d "/" -f1)
          echo ${registry_host}
          sed -i "s/registry.local:5000/${registry_host}:5000/g" infrastructure/tilt/values-dev.yaml
          cat infrastructure/tilt/values-dev.yaml
      - name: Run tilt up
        run: |
          tilt ci -f Tiltfile

#registry_host=$(docker network inspect -f '{{json .Containers}}' k3d-perspex-local | jq -r '.[] | .Name + ":" + .IPv4Address' | grep -o 'registry.localhost:[^"]*' | cut -d ":" -f2- | tr -d /16)
#docker network inspect -f '{{json .Containers}}' k3d-perspex-local | jq -r '.[] | .Name + ":" + .IPv4Address' | grep -o 'registry.localhost:[^"]*' | cut -d ":" -f2 | cut -d "/" -f1
#| tr -d /16
