name: codegen-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
    paths:
      - "services/migration/**/*.sql"
      - "schemas/graphql/**.graphql"
      - ".github/workflows/codegen-linter.yml"

jobs:
  codegen-linter:
    name: Codegen Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update checkout
        run: git fetch --prune
        shell: bash

      - name: Set environment variables
        id: set-environment-variables
        run: |
          echo "TILT_BACKEND_ENABLED=false" >> ${GITHUB_ENV}
          echo "TILT_MIGRATION_ENABLED=true" >> ${GITHUB_ENV}
          echo "TILT_REMOTE_CLUSTER=False" >> ${GITHUB_ENV}
          echo "TILT_BACKEND_IMAGE_TARGET=deployable" >> ${GITHUB_ENV}

      - name: Run helm dependency update
        run: |
          bin/helm dependency update infrastructure/charts/perspex

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - uses: AbsaOSS/k3d-action@v2
        name: "Spin up k3d"
        with:
          cluster-name: "perspex-ci"
          args: >-
            -c infrastructure/tilt/k3d-config.yaml

      - name: Do some yaml substitutions
        run: |
          bin/yq eval -i '.backend.enabled = "${TILT_BACKEND_ENABLED}"' infrastructure/tilt/values-dev.yaml

      - name: Run tilt up
        run: |
          bin/tilt ci -f Tiltfile

      - name: Verify Codegen is committed
        run: |
          bin/codegen-linter.sh
