name: codegen-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
    paths:
      - ".github/workflows/codegen-linter.yml"
      - "services/migration/**/*.sql"
      - "schemas/graphql/**.graphql"
      - "schemas/openapi/**/*"
      - "schemas/proto/**/*"

jobs:
  codegen-linter:
    name: Codegen Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update checkout
        run: git fetch --prune
        shell: bash

      - name: Verify Codegen is committed
        run: |
          bin/codegen-linter.sh -l
