name: codegen-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
    paths:
      - ".github/workflows/codegen-linter.yml"
      - "services/migration/**/*.sql"
      - "schemas/graphql/**.graphql"
      - "schemas/openapi/**/*"
      - "schemas/proto/**/*"

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.ts}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.ts}}

  codegen-linter:
    name: Codegen Linter
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: update checkout
        run: git fetch
        shell: bash

      - name: fetch from main
        run: git fetch origin main

      - name: Verify Codegen is committed
        run: |
          bin/codegen-linter.sh -l

      # - name: Set environment variables
      #   id: set-environment-variables
      #   run: |
      #     echo "TILT_BACKEND_ENABLED=false" >> ${GITHUB_ENV}
      #     echo "TILT_MIGRATION_ENABLED=true" >> ${GITHUB_ENV}
      #     echo "TILT_REMOTE_CLUSTER=False" >> ${GITHUB_ENV}
      #     echo "TILT_BACKEND_IMAGE_TARGET=deployable" >> ${GITHUB_ENV}

      # - name: Run helm dependency update
      #   run: |
      #     bin/helm dependency update infrastructure/charts/perspex

      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9.7'

      # - name: Spin up k3d cluster
      #   run: |
      #     bin/k3d cluster create -c infrastructure/tilt/k3d-config.yaml

      # - name: Do some yaml substitutions
      #   run: |
      #     bin/yq eval -i '.backend.enabled = "${TILT_BACKEND_ENABLED}"' infrastructure/tilt/values-dev.yaml

      # - name: Run tilt up
      #   run: |
      #     bin/tilt ci -f Tiltfile

