
name: migration-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
jobs:
  migration-linter:
    name: Migration Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update checkout
        run: git fetch --prune
        shell: bash

      - uses: sbdchd/squawk-action@v1
        with:
          pattern: ${{ steps.modified-migrations.outputs.file_names }}
